
export const GET_TOKEN_STARTED = 'GET_TOKEN_STARTED'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'

export const DARK_THEME = 'DARK_THEME'
export const LIGHT_THEME = 'LIGHT_THEME'

export const IDS_LIKED_TRACKS = 'IDS_LIKED_TRACKS'
