
export const VALIDATE_USER_STARTED = 'VALIDATE_USER_STARTED'
export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS'
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE'

export const GET_TOKEN_STARTED = 'GET_TOKEN_STARTED'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'

export const DARK_THEME = 'DARK_THEME'
export const LIGHT_THEME = 'LIGHT_THEME'
