export const GET_TOKEN_STARTED = 'GET_TOKEN_STARTED'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'

export const DARK_THEME = 'DARK_THEME'
export const LIGHT_THEME = 'LIGHT_THEME'

export const IDS_CURRENT_TRACKS = 'IDS_CURRENT_TRACKS'
export const IDS_LIKED_TRACKS = 'IDS_LIKED_TRACKS'

export const GET_TRACK_STARTED = 'GET_TRACK_STARTED'
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS'
export const GET_TRACK_FAILURE = 'GET_TRACK_FAILURE'

export const GET_PREV_TRACK_STARTED = 'GET_PREV_TRACK_STARTED'
export const GET_PREV_TRACK_SUCCESS = 'GET_PREV_TRACK_SUCCESS'
export const GET_PREV_TRACK_FAILURE = 'GET_PREV_TRACK_FAILURE'

export const GET_NEXT_TRACK_STARTED = 'GET_NEXT_TRACK_STARTED'
export const GET_NEXT_TRACK_SUCCESS = 'GET_NEXT_TRACK_SUCCESS'
export const GET_NEXT_TRACK_FAILURE = 'GET_NEXT_TRACK_FAILURE'

export const TRACKS_BY_DATE = 'TRACKS_BY_DATE'
export const TRACKS_BY_AUTHOR = 'TRACKS_BY_AUTHOR'
export const TRACKS_BY_GENRE = 'TRACKS_BY_GENRE'

export const ALL_TRACKS = 'ALL_TRACKS'
export const SEARCHED_TRACKS = 'SEARCHED_TRACKS'
